### ISSUE TITLE
test_clear_bit() fails

### ISSUE THREAD

**Issue by andygrove** [jihoonson/iron-arrow#1]
I'm getting this test failure:

```
---- common::bit_util::test::test_clear_bit stdout ----
	thread 'common::bit_util::test::test_clear_bit' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', src/common/bit_util.rs:159:5
```

Here is the code. It looks like the test expected newly allocate memory to be initialized to zero but it is not?

```
    buffer.reserve(5);

    let mut data = buffer.data_as_mut();
    assert_eq!(false, get_bit(data, 2));
```

**Comment by andygrove** [comment]
I tracked this down. Here is a PR to fix this.

https://github.com/jihoonson/iron-arrow/pull/2

**Comment by jihoonson** [comment]
@andygrove thanks for debugging this! I left a comment on your PR.
