### ISSUE TITLE
Publish crate to crates.io

### ISSUE THREAD

**Issue by andygrove** [jihoonson/iron-arrow#3]
It would be nice if you could publish this to crates.io so I can have a dependency on it from my project. I would be happy to help you with this.

Do you think it is stable enough for people to start using?

**Comment by jihoonson** [comment]
Hi @andygrove, I don't think it's stable enough. At least some more basic functionalities should be implemented. Also, IMO, it would be better to donate this code to Apache Arrow first. I was thinking to donate when some basic functionalities are implemented, but unfortunately, I couldn't spend my time for this project for recent few months. 

It would be great if it's possible to donate now, but i'm not sure. @wesm what do you think?

**Comment by wesm** [comment]
It would make sense to donate if there is a definite plan to continue developing the codebase. Some Apache projects have had bad experiences with code being donated then abandoned

**Comment by andygrove** [comment]
I would like to start contributing to this project. I think it would make sense to start publishing this to crates.io as a 0.1.x release (there really is nothing to lose by doing this) and I can help build some momentum around the project too once I'm a little more up to speed.

I don't think we need to rush to donate, and I have some potential users lined up for DataFusion that could help test this codebase.

**Comment by jihoonson** [comment]
@wesm thanks. It makes sense.

@andygrove ok, that sounds good. Would you help me to publish?

**Comment by andygrove** [comment]
I can help with publishing this. Here are the docs: https://doc.rust-lang.org/cargo/reference/publishing.html

Main thing is including all the needed info in Cargo.toml and I can create a PR for that soon.

**Comment by andygrove** [comment]
Here is PR to update cargo.toml - https://github.com/jihoonson/iron-arrow/pull/4

After this you can just "cargo publish"

**Comment by wesm** [comment]
Again, please let me know if you all intend to actively develop / maintain the Rust bindings -- if so it would be great to house this effort under the Apache project

**Comment by andygrove** [comment]
@wesm Now that I've converted my project to columnar, I'm ready to move to Arrow, so yes, I think it would make sense to do this under Apache project. I have to write serialization code to move data around and Arrow is going to make that much easier.

**Comment by jihoonson** [comment]
@wesm I don't have a specific plan yet. Probably I can work on some easy issues during weekend, but I think it won't be enough. @andygrove do you have any plan for actively developing this project?

**Comment by LukeMathWalker** [comment]
I was looking into in-memory data structures, data pipeline tools and similar stuff and I came across @andygrove Datafusion project. At the same time I am working as a professional ML developer, using Python as the main tool, so Arrow rings a bell when it comes to have a zero-copy in-memory data structure shareable between different environments.

I am a newbie Rust developer, but if @andygrove is happy to teach and mentor me I'd be happy to contribute to this project!

**Comment by jihoonson** [comment]
Fixed via #4.
